name: Publish to github.io
on:
  workflow_dispatch:
permissions:
  id-token: write
  pages: write
jobs:
  build-and-publish:
    name: Build And Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build --workspace=packages/ui
      - uses: actions/upload-pages-artifact@v3
        with:
          path: packages/ui/dist
      - uses: actions/deploy-pages@v4